//------------------------------------------------------------------------
// GameTest.cpp
//------------------------------------------------------------------------
#include "stdafx.h"
//------------------------------------------------------------------------
#include <windows.h> 
#include <math.h>  
#include <vector>
//------------------------------------------------------------------------
#include "app\app.h"
#include "Deck.h"
#include "Card.h"
#include "Map.h"
#include "Player.h"
using namespace App;
//------------------------------------------------------------------------

//------------------------------------------------------------------------
// Sample data....
//------------------------------------------------------------------------
//CSimpleSprite *testSprite;
CSimpleSprite* player;
CSimpleSprite* tileWall;
CSimpleSprite* tileFloor;
CSimpleSprite* tileDoor;
vector<float>x;
vector<float>y;

enum
{
	ANIM_FORWARDS,
	ANIM_BACKWARDS,
	ANIM_LEFT,
	ANIM_RIGHT,
};


//------------------------------------------------------------------------

//------------------------------------------------------------------------
// Called before first update. Do any initial setup here.
//------------------------------------------------------------------------
void Init()
{
	//------------------------------------------------------------------------
	// Example Sprite Code....

	float startValue = 32.0f;
	for (int i = 0; i < 32; i++) {
		x.push_back(startValue * i);
		y.push_back(startValue * i);
	}

	//testSprite = CreateSprite(".\\TestData\\Test.bmp", 8, 4);
	//testSprite->SetPosition(400.0f, 400.0f);
	player = CreateSprite(".\\TestData\\player.png", 6, 10);
	float speed = 1.0f / 15.0f;
	//testSprite->CreateAnimation(ANIM_BACKWARDS, speed, { 0,1,2,3,4,5,6,7 });
	//testSprite->CreateAnimation(ANIM_LEFT, speed, { 8,9,10,11,12,13,14,15 });
	//testSprite->CreateAnimation(ANIM_RIGHT, speed, { 16,17,18,19,20,21,22,23 });
	//testSprite->CreateAnimation(ANIM_FORWARDS, speed, { 24,25,26,27,28,29,30,31 });
	//testSprite->SetScale(1.0f);

	player->CreateAnimation(ANIM_BACKWARDS, speed, { 48,49,50,51,52,53,});
	player->CreateAnimation(ANIM_LEFT, speed, { 41,40,39,38,37,26, });
	player->CreateAnimation(ANIM_RIGHT, speed, { 36,37,38,39,40,41, });
	player->CreateAnimation(ANIM_FORWARDS, speed, { 30,31,32,33,34, });
	player->SetScale(1.5f);

	tileWall = CreateSprite(".\\TestData\\stone2_dark3.png", 1, 1);
	tileWall->SetScale(1.5f);
	tileFloor = CreateSprite(".\\TestData\\ice0.png", 1, 1);
	tileFloor->SetScale(1.5f);
	tileDoor = CreateSprite(".\\TestData\\dngn_closed_door.png", 1, 1);
	tileDoor->SetScale(1.5f);
	//tileWall->SetPosition(0.0f, 32.0f);



	//------------------------------------------------------------------------
}

//------------------------------------------------------------------------
// Update your simulation here. deltaTime is the elapsed time since the last update in ms.
// This will be called at no greater frequency than the value of APP_MAX_FRAME_RATE
//------------------------------------------------------------------------
void Update(float deltaTime)
{
	//------------------------------------------------------------------------
	// Example Sprite Code....
	//testSprite->Update(deltaTime);
	player->Update(deltaTime);
	if (App::GetController().GetLeftThumbStickX() > 0.5f)
	{
		player->SetAnimation(ANIM_RIGHT);
		float x, y;
		player->GetPosition(x, y);
		x += 1.0f;
		player->SetPosition(x, y);
	}
	if (App::GetController().GetLeftThumbStickX() < -0.5f)
	{
		player->SetAnimation(ANIM_LEFT);
		float x, y;
		player->GetPosition(x, y);
		x -= 1.0f;
		player->SetPosition(x, y);
	}
    if (App::GetController().GetLeftThumbStickY() > 0.5f)
    {
		player->SetAnimation(ANIM_FORWARDS);
        float x, y;
		player->GetPosition(x, y);
        y += 1.0f;
		player->SetPosition(x, y);
    }
	if (App::GetController().GetLeftThumbStickY() < -0.5f)
	{
		player->SetAnimation(ANIM_BACKWARDS);
		float x, y;
		player->GetPosition(x, y);
		y -= 1.0f;
		player->SetPosition(x, y);
	}
	if (App::GetController().CheckButton(XINPUT_GAMEPAD_DPAD_UP, false))
	{
		player->SetScale(player->GetScale() + 0.1f);
	}
	if (App::GetController().CheckButton(XINPUT_GAMEPAD_DPAD_DOWN, false))
	{
		player->SetScale(player->GetScale() - 0.1f);
	}
	if (App::GetController().CheckButton(XINPUT_GAMEPAD_DPAD_LEFT, false))
	{
		player->SetAngle(player->GetAngle() + 0.1f);
	}
	if (App::GetController().CheckButton(XINPUT_GAMEPAD_DPAD_RIGHT, false))
	{
		player->SetAngle(player->GetAngle() - 0.1f);
	}
	if (App::GetController().CheckButton(XINPUT_GAMEPAD_A, true))
	{
		player->SetAnimation(-1);
	}
	//------------------------------------------------------------------------
	// Sample Sound.
	//------------------------------------------------------------------------
	if (App::GetController().CheckButton(XINPUT_GAMEPAD_B, true))
	{
		App::PlaySound(".\\TestData\\Test.wav");
	}
}

//------------------------------------------------------------------------
// Add your display calls here (DrawLine,Print, DrawSprite.) 
// See App.h 
//------------------------------------------------------------------------
void Render()
{	
	//------------------------------------------------------------------------
	// Example Sprite Code....
	//testSprite->Draw();
	//------------------------------------------------------------------------
	int rowNumber = 0;
	//Row 1
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 2
	rowNumber++;
	tileFloor->SetPosition(x[0], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[1], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[2], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[3], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[4], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[5], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 3
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[4], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 4
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[4], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 5
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[4], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 6
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[4], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[5], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[6], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[7], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 7
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 8
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 9
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 10
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 11
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 12
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 13
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[8], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[9], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[10], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[11], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[12], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[13], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[14], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 14
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 15
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 16
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 17
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[21], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[22], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[23], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[24], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[25], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[26], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[27], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[28], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[29], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[30], y[rowNumber]);
	tileFloor->Draw();
	tileDoor->SetPosition(x[31], y[rowNumber]);
	tileDoor->Draw();

	//Row 18
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[21], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 19
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[21], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 20
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[21], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 21
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileFloor->SetPosition(x[15], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[16], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[17], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[18], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[19], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[20], y[rowNumber]);
	tileFloor->Draw();
	tileFloor->SetPosition(x[21], y[rowNumber]);
	tileFloor->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 22
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 23
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();
	
	//Row 24
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 25
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 26
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 27
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 28
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 29 
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 30
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	//Row 31
	rowNumber++;
	tileWall->SetPosition(x[0], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[1], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[2], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[3], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[4], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[5], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[6], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[7], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[8], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[9], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[10], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[11], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[12], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[13], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[14], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[15], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[16], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[17], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[18], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[19], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[20], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[21], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[22], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[23], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[24], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[25], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[26], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[27], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[28], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[29], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[30], y[rowNumber]);
	tileWall->Draw();
	tileWall->SetPosition(x[31], y[rowNumber]);
	tileWall->Draw();

	player->Draw();

	//------------------------------------------------------------------------
	// Example Text.
	//------------------------------------------------------------------------
	App::Print(100, 100, "Sample Text");

	//------------------------------------------------------------------------
	// Example Line Drawing.
	//------------------------------------------------------------------------
	
	//static float a = 0.0f;
	//float r = 1.0f;
	//float g = 1.0f;
	//float b = 1.0f;
	//a += 0.1f;
	//for (int i = 0; i < 20; i++)
	//{

		//float sx = 200 + sinf(a + i * 0.1f)*60.0f;
		//float sy = 200 + cosf(a + i * 0.1f)*60.0f;
		//float ex = 700 - sinf(a + i * 0.1f)*60.0f;
		//float ey = 700 - cosf(a + i * 0.1f)*60.0f;
		//g = (float)i / 20.0f;
		//b = (float)i / 20.0f;
		//App::DrawLine(sx, sy, ex, ey,r,g,b);
	//}
}
//------------------------------------------------------------------------
// Add your shutdown code here. Called when the APP_QUIT_KEY is pressed.
// Just before the app exits.
//------------------------------------------------------------------------
void Shutdown()
{	
	//------------------------------------------------------------------------
	// Example Sprite Code....
	delete player;
	delete tileWall;
	delete tileFloor;
	delete tileDoor;
	//------------------------------------------------------------------------
}